name: "Check Certificate"

on: [push]


jobs:
  check-certificate:
    runs-on: ubuntu-latest
    steps:
      - name: Probe certificate of *.ubiid.ch
        id: probe_cert
        run: | 
          notAfter=$(echo \
            | openssl s_client -servername autoid.ubiid.ch -connect autoid.ubiid.ch:443 2>/dev/null \
            | openssl x509 -noout -dates \
            | grep notAfter)
          echo "::set-output name=notAfter::${notAfter/notAfter=/}"

      - name: Show exipration date
        id: debug
        run: |
          echo ${{ steps.probe_cert.outputs.notAfter }}

      - name: Check if the cert is about to expire
        id: calculate_dates_til_expires
        run: |
          notAfter="${{ steps.probe_cert.outputs.notAfter }}"

          datediff() {
            d1=$(date -d "$1" +%s)
            d2=$(date -d "$2" +%s)
            echo $(( (d1 - d2) / 86400 ))
          }

          days=$(datediff "$notAfter" "$(date)")

          echo "::set-output name=daysLeft::${days}"
          