name: "Check Certificate"

on: [push]


jobs:
  check-certificate:
    runs-on: ubuntu-latest
    steps:
      - name: Probe certificate of *.ubiid.ch
        id: probe_cert
        run: | 
          notAfter=$(echo \
            | openssl s_client -servername autoid.ubiid.ch -connect autoid.ubiid.ch:443 2>/dev/null \
            | openssl x509 -noout -dates \
            | grep notAfter)
          echo "::set-output name=notAfter::${notAfter/notAfter=/}"
      - name: Show exipration date
        id: debug
        run: |
          echo ${{ steps.probe_cert.outputs.notAfter }}
          